version: "3"

networks:
  loki:

services:
  hermes:
    build: ./
    ports:
      - "8080:8080"
    environment:
      - LOKI_INGEST_ENDPOINT=http://loki:3100
    networks:
      - loki
  loki:
    image: grafana/loki:2.4.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.4.1
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki
