version: "3"

networks:
  loki:

services:
  hermes:
    build: ./
    ports:
      - "8080:8080"
    environment:
      - LOKI_INGEST_ENDPOINT=http://loki:3100
    networks:
      - hermes
  clickhouse:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./db:/var/lib/clickhouse
      - ./clickhouse_config/config.xml:/etc/clickhouse-server/config.xml
    networks:
      - hermes
